# Generated by Django 5.0.1 on 2024-08-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('business_location', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('product', models.CharField(max_length=50)),
            ],
        ),
    ]
